name: SpiderSense
version: '${project.version}'
main: org.padrewin.spidersense.SpiderSense
api-version: '1.20'
author: 'padrewin'
commands:
  spidersense:
    description: Total access to the plugin commands.
    permission: spidersense.admin