#########################################################################################################
#    Plugin now supports full hex color codes.                                                          #
#    You can use https://www.birdflop.com/resources/rgb/ to create your colors                          #
#    Developer; padrewin || Cold Development                                                            #
#    GitHub; https://github.com/padrewin || https://github.com/Cold-Development                         #
#    Links: https://colddev.dev || https://discord.colddev.dev                                          #
#########################################################################################################

# Messages prefix:
plugin-prefix: "&8「&#003254Sp&#18476Cid&#305C83er&#49709BSe&#6185B2ns&#6185B2e&8」&7» "

# Messages shown in chat:
removed-message: "&7Your placed cobwebs have been &cremoved&7!"
reload-message: "&7Config &areloaded&7."
no-permission-message: "&cYou don't have permission to do that."
shutdown-message: "&cCobwebs have been removed because the server is restarting."

# This setting defines the delay before cobweb blocks are automatically removed after being placed.
# The value is in seconds. For example, if set to 300, cobwebs placed will be removed after 5 minutes.
cobweb-timer: 300